spring:
  main:
    allow-circular-references: true
bulkhead-rate-limit:
  enabled: true
  metrics-enabled: true
  default-policy: default
  policies:
    default:
      bulkhead:
        max-concurrent-calls: 3      # Máximo 3 chamadas simultâneas
        max-queue-size: 2            # Até 2 requisições podem esperar
        queue-timeout: 5000ms        # Timeout de 5 segundos na fila
      rate-limit:
        limit: 5                     # Máximo 5 chamadas
        window: 10s                  # Janela de 10 segundos
